# Generated by Django 4.2.4 on 2023-09-06 17:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_rename_entry_entries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entries',
            new_name='Note',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='entry_id',
            new_name='id',
        ),
    ]
